# Generated by Django 6.0.1 on 2026-01-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banners", "0002_banner_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={"ordering": ["order"]},
        ),
    ]
