# Generated by Django 6.0.1 on 2026-01-23 16:09

import uuid
import django.db.models.deletion
from django.db import migrations, models


def generate_order_tokens(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    for order in Order.objects.filter(public_token__isnull=True):
        order.public_token = uuid.uuid4()
        order.save(update_fields=["public_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_session_key"),
    ]

    operations = [
        # 1️⃣ Remove old FK (correct)
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),

        # 2️⃣ Add address → order link (correct)
        migrations.AddField(
            model_name="address",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_address",
                to="orders.order",
            ),
        ),

        # 3️⃣ Add token field WITHOUT unique
        migrations.AddField(
            model_name="order",
            name="public_token",
            field=models.UUIDField(
                null=True,
                editable=False
            ),
        ),

        # 4️⃣ Backfill tokens for existing orders
        migrations.RunPython(generate_order_tokens),

        # 5️⃣ Enforce uniqueness AFTER data exists
        migrations.AlterField(
            model_name="order",
            name="public_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                editable=False
            ),
        ),
    ]
