# Generated by Django 6.0.1 on 2026-01-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_remove_order_status_order_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
