# Generated by Django 6.0.1 on 2026-02-26 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_address_email_order_tax_amount"),
        ("products", "0006_remove_product_image_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
            ),
        ),
    ]
