# Generated by Django 6.0.1 on 2026-01-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_slug_alter_subcategory_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="product",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
